name: need
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - Assets/logo.jpg
    - Assets/app_goals_image.jpg
    - Assets/special feature.png
    - Assets/Smart ai image.png
  fonts:
    - family: RedditSans
      fonts:
        - asset: Assets/fonts/Reddit_Sans/static/RedditSans-Black.ttf
        - asset: Assets/fonts/Reddit_Sans/static/RedditSans-Bold.ttf
          weight: 700
        - asset: Assets/fonts/Reddit_Sans/static/RedditSans-Regular.ttf